get http://localhost:8080/compareFaces

###
POST http://localhost:8080/blocked/userId/DyGwmJ80JrSugovlv0x4R3ljQBp1/blockedUserId/f4bi3hjgc6ife





###
GET http://localhost:8080/blocked/blockedUsers/DyGwmJ80JrSugovlv0x4R3ljQBp1


###

GET http://localhost:8080/connect/connectedUsers/DyGwmJ80JrSugovlv0x4R3ljQBp1



###
GET http://localhost:8080/connect/DyGwmJ80JrSugovlv0x4R3ljQBp1

###
POST http://localhost:8080/blocked/userId/DyGwmJ80JrSugovlv0x4R3ljQBp1/unBlockedUserId/f4bi3hjgc6ife
